# fly.toml app configuration file generated for mandril-bot on 2023-09-18T12:32:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mandril-bot"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
